INSERT INTO airdrops (name, description, token, protocol, chain, estimated_value, ends_at, is_active, website_url) VALUES
('LayerZero Airdrop',        'Cross-chain messaging protocol rewarding early bridge users and liquidity providers.',           'ZRO',   'LayerZero',    'Multi-chain',  2500.00, now() + INTERVAL '12 days', true,  'https://layerzero.network'),
('zkSync Era Airdrop',       'ZK-rollup network token distribution for early testnet participants and mainnet users.',         'ZK',    'zkSync Era',   'Ethereum L2',  1800.00, now() + INTERVAL '5 days',  true,  'https://zksync.io'),
('Starknet Airdrop',         'Cairo-based ZK rollup rewarding developers and early users with STRK governance tokens.',       'STRK',  'StarkNet',     'Ethereum L2',  1400.00, now() + INTERVAL '8 days',  true,  'https://starknet.io'),
('Scroll Airdrop',           'ZK-EVM rollup token claiming for bridge, swap, and lending protocol early adopters.',           'SCR',   'Scroll',       'Ethereum L2',  950.00,  now() + INTERVAL '20 days', true,  'https://scroll.io'),
('Linea Airdrop',            'ConsenSys-backed zkEVM rewarding Voyage campaign participants and DeFi power users.',           'LINEA', 'Linea',        'Ethereum L2',  720.00,  now() + INTERVAL '3 days',  true,  'https://linea.build'),
('EigenLayer Restaking',     'Restaking protocol airdrop for ETH stakers who delegated to AVS operators.',                   'EIGEN', 'EigenLayer',   'Ethereum',     3100.00, now() + INTERVAL '15 days', true,  'https://eigenlayer.xyz'),
('Hyperliquid Airdrop',      'Perpetuals DEX on its own L1 — top traders and volume generators qualify.',                    'HYPE',  'Hyperliquid',  'Hyperliquid',  4200.00, now() + INTERVAL '1 day',   true,  'https://hyperliquid.xyz'),
('Wormhole Airdrop',         'Cross-chain interoperability protocol rewarding early bridging activity across 20+ chains.',    'W',     'Wormhole',     'Multi-chain',  870.00,  now() + INTERVAL '7 days',  true,  'https://wormhole.com'),
('dYdX Chain Migration',     'Trade-and-earn incentive for v3→v4 migrators on the dYdX sovereign Cosmos chain.',             'DYDX',  'dYdX',         'Cosmos',       620.00,  now() + INTERVAL '25 days', true,  'https://dydx.exchange'),
('Blast Airdrop',            'Yield-bearing L2 rewarding early depositors, developers, and community contributors.',         'BLAST', 'Blast',        'Ethereum L2',  1100.00, now() + INTERVAL '10 days', true,  'https://blast.io');
